
# Project: Review of multifunctionality in ecology, conservation and ecosystem service science

# Title: Process neutral model data to test the number of functions

# load relevant libraries
library(here)

# clear the current memory
rm(list = ls())

# process this model data

# load scripts with processing functions
source(here("Scripts/process_model_data.R"))

# load three function matrices (generated by Laura Byrne)
f.list <- list.files(path = here("data"))
fm_names <- f.list[grepl(pattern = "SpeciesIDs", f.list)]

# load these data.frames into a list
library(readr)

func.list <- vector("list", length = length(fm_names))
for (i in 1:length(func.list)) {
  
  x <- read_csv(file = paste(here("data"), fm_names[i], sep = "/") )
  colnames(x)[1] <- "species"
  
  func.list[[i]] <- x
  
}


# read the model data from the data folder
# this list is generated using the drift_model_number_functions.R script
drift.mod.list <- read_csv(here("data/drift_model_n_functions.csv"))

# for each dataset in drift.mod.list and for each function matrix in func.list
# process the data

func.reps <- vector("list", length = length(func.list))
for (j in 1:length(func.list)) {
  
  # process the simulated cluster using: process_sim_data
  df.proc <- 
    process_sim_data(model_data = drift.mod.list, 
                     func.mat =  func.list[[j]], 
                     time_final = TRUE, 
                     species_abun = "raw")
  
  # add this to a list
  func.reps[[j]] <- df.proc
  
}

# bind this list into a data.frame  
mod.out <- bind_rows(func.reps, .id = "function_matrix")
View(mod.out)

# add a unique model-ID variable
mod.out <- 
  mod.out %>%
  mutate(mod_id = paste(drift_parameter, function_matrix, model_run, sep = ".")) %>%
  select(mod_id, drift_parameter, function_matrix, model_run:F_5)

# check the model parameters
length(unique(mod.out$mod_id))
head(mod.out)

# write this model data.frame into a .csv file so the model does not have to be re-run

# make a folder to export the cleaned data
if(! dir.exists(here("data"))){
  dir.create(here("data"))
}

write_csv(x = mod.out, file = here("data/drift_model_n_functions_processed.csv"))

### END
